force-app/main/default/objects/Contact_Information_Detail__mdt/Contact_Information_Detail__mdt.object-meta.xml
<CustomObject>
    <label>Contact Information Detail</label>
    <pluralLabel>Contact Information Detail</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Information_Detail__mdt/fields/Bold__c.field-meta.xml
<CustomField>
    <fullName>Bold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Information_Detail__mdt/fields/Contact_Information_Header__c.field-meta.xml
<CustomField>
    <fullName>Contact_Information_Header__c</fullName>
    <label>Contact Information Header</label>
    <referenceTo>Contact_Information_Header__mdt</referenceTo>
    <relationshipLabel>Contact Information Detail</relationshipLabel>
    <relationshipName>Contact_Information_Detail</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Contact_Information_Detail__mdt/fields/CSS_Class__c.field-meta.xml
<CustomField>
    <fullName>CSS_Class__c</fullName>
    <defaultValue>&quot;slds-text-body_regular&quot;</defaultValue>
    <description>Populating from standard SF CCS text Classes from link below. Please update the picklist if necessary 

https://spring-20.lightningdesignsystem.com/utilities/text/</description>
    <label>CSS Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>slds-text-body_regular</fullName>
                <default>true</default>
                <label>slds-text-body_regular</label>
            </value>
            <value>
                <fullName>slds-text-body_small</fullName>
            </value>
            <value>
                <fullName>slds-text-heading_large</fullName>
            </value>
            <value>
                <fullName>slds-text-heading_medium</fullName>
            </value>
            <value>
                <fullName>slds-text-heading_small</fullName>
            </value>
            <value>
                <fullName>slds-text-title</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Information_Detail__mdt/fields/Hide_Label__c.field-meta.xml
<CustomField>
    <fullName>Hide_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Information_Detail__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>DataTable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Information_Header__mdt/Contact_Information_Header__mdt.object-meta.xml
<CustomObject>
    <label>Contact Information Header</label>
    <pluralLabel>Contact Information Header</pluralLabel>
</CustomObject>

force-app/main/default/classes/CGS_ContactInfoControllerTest.cls
@istest
public with sharing class CGS_ContactInfoControllerTest 
{
    @istest
    public static void testCGS_GlobalContactInfo()
    {
        CGS_GlobalContactInfo GContactInfo = new CGS_GlobalContactInfo();
        
        string defaultValue = string.valueOf(GContactInfo.getDefaultValue());
        System.assertNotEquals( null, defaultValue, 'No Default Value found' );
        
        defaultValue = string.valueOf(GContactInfo.getValues() );
        System.assertNotEquals( null, defaultValue, 'No Values found' );
    }

    @istest
    public static void TestCGS_ContactInfoControllerHandleresult() 
    {
        Test.startTest();
        
        //***** Testing handleresult
        CGS_ContactInfoController callback = new CGS_ContactInfoController();       
        // Create test result and context objects.
        Metadata.DeployResult result = new Metadata.DeployResult();
        result.numberComponentErrors = 1;
        Metadata.DeployCallbackContext context = new Metadata.DeployCallbackContext();

        // Invoke the callback's handleResult method.
        callback.handleResult(result, context);
        
        Test.stopTest();
        
    }

    @istest
    public static void TestCGS_ContactInfoControllerGetRecords() 
    {
		List<Contact_Information_Header__mdt> CIH_MDTList = 
            [select id, MasterLabel from Contact_Information_Header__mdt]; 
        system.debug(CIH_MDTList[0].id) ;
        
        Test.startTest();
                
        //**** Testing getRecords  
        //with Valid Id      
        CGS_ContactInfoController.lwcData lwcData = CGS_ContactInfoController.getRecords(CIH_MDTList[0].id);        
        System.assertNotEquals( 0, lwcData.ContactInfoDetailList.size(), 'No lwc Data Return' );
        
        //with Invalid Id 
        lwcData = CGS_ContactInfoController.getRecords(null); 
        System.assertEquals(0, lwcData.ContactInfoDetailList.size(), 'Not lwc Data Return' );
        
        Test.stopTest();
        
    }


    @istest
    public static void TestCGS_ContactInfoController() 
    {
		List<Contact_Information_Header__mdt> CIH_MDTList = 
            [select id, MasterLabel from Contact_Information_Header__mdt]; 
        system.debug(CIH_MDTList[0].id) ;
        
        Test.startTest();
        
        //**** Testing updateMetadataContact        
        List<Contact_Information_Detail__mdt> CID_MDTList = 
            [select id, MasterLabel, DeveloperName, Type__c, Sequence__c, Value__c, 
                Hide_Label__c, CSS_Class__c, Bold__c
                from Contact_Information_Detail__mdt 
                where Contact_Information_Header__c = :CIH_MDTList[0].id
                    and Type__c = 'Text' order by Sequence__c];
        
        //***** Testing 
        Map<string, string> fieldsToUpdateMap = new Map<string, string>();
        fieldsToUpdateMap.put(CID_MDTList[0].DeveloperName, 'Test');
        String fieldsToUpdate = JSON.serialize(fieldsToUpdateMap);
        System.debug('fieldsToUpdate: ' + fieldsToUpdate);
        
        Map<string, boolean> fieldsBoldToUpdateMap = new Map<string, boolean>();
        fieldsBoldToUpdateMap.put(CID_MDTList[0].DeveloperName, true);
        String fieldsBoldToUpdate = JSON.serialize(fieldsBoldToUpdateMap);
        System.debug('fieldsBoldToUpdate: ' + fieldsBoldToUpdate);
        
        Map<string, boolean> fieldsHideLabelToUpdateMap = new Map<string, boolean>();
        fieldsHideLabelToUpdateMap.put(CID_MDTList[0].DeveloperName, true);
        String fieldsHideLabelToUpdate = JSON.serialize(fieldsHideLabelToUpdateMap);
        System.debug('fieldsHideLabelToUpdate: ' + fieldsHideLabelToUpdate);
        
        Map<string, integer> fieldsSequenceToUpdateMap = new Map<string, integer>();
        fieldsSequenceToUpdateMap.put(CID_MDTList[0].DeveloperName, 20);
        String fieldsSequenceToUpdate = JSON.serialize(fieldsSequenceToUpdateMap);
        System.debug('fieldsSequenceToUpdate: ' + fieldsSequenceToUpdate);
        
        Map<string, string> fieldsCSSClassToUpdateMap = new Map<string, string>();
        fieldsCSSClassToUpdateMap.put(CID_MDTList[0].DeveloperName, 'abc');
        String fieldsCSSClassToUpdate = JSON.serialize(fieldsCSSClassToUpdateMap);
        System.debug('fieldsCSSClassToUpdate: ' + fieldsCSSClassToUpdate);
        
        CGS_ContactInfoController.updateMetadataContact(fieldsToUpdate, fieldsBoldToUpdate, 
                                                        fieldsHideLabelToUpdate, fieldsCSSClassToUpdate, 
                                                        fieldsSequenceToUpdate);
        Test.stopTest();
        
    }
}